Models/Tarea.cs
using System;
using System.Collections.Generic;

namespace MiniCore.Models;

public partial class Tarea
{
    public int Id { get; set; }

    public string Nombredelatarea { get; set; } = null!;

    public DateOnly? FechadeInicio { get; set; }

    public double? TiempoEstimado { get; set; }

    public string? EstadoProgreso { get; set; }

    public int? ProyectoId { get; set; }

    public int? EmpleadoId { get; set; }

    public virtual Empleado? Empleado { get; set; }

    public virtual Proyecto? Proyecto { get; set; }
}

Controllers/TareasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MiniCore.Models;

namespace MiniCore.Controllers
{
    public class TareasController : Controller
    {
        private readonly MinicoreContext _context;
        private object fechaInicio;
        private object fechaFin;

        public TareasController(MinicoreContext context)
        {
            _context = context;
        }

        // GET: Tareas
        public async Task<IActionResult> Index(DateOnly? fechaInicio, DateOnly? fechaFin)
        {
            IQueryable<Tarea> query = _context.Tareas.Include(t => t.Empleado).Include(t => t.Proyecto);

            if (fechaInicio != null && fechaFin != null)
            {
                query = query.Where(t => t.FechadeInicio >= fechaInicio && t.FechadeInicio <= fechaFin);
            }

            var tareas = await query.ToListAsync();

            ViewData["fechaInicio"] = fechaInicio;
            ViewData["fechaFin"] = fechaFin;

            return View(tareas);
        }


        // GET: Tareas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarea = await _context.Tareas
                .Include(t => t.Empleado)
                .Include(t => t.Proyecto)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tarea == null)
            {
                return NotFound();
            }

            return View(tarea);
        }

        // GET: Tareas/Create
        public IActionResult Create()
        {
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id");
            ViewData["ProyectoId"] = new SelectList(_context.Proyectos, "Id", "Id");
            return View();
        }

        // POST: Tareas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombredelatarea,FechadeInicio,TiempoEstimado,EstadoProgreso,ProyectoId,EmpleadoId")] Tarea tarea)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tarea);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id", tarea.EmpleadoId);
            ViewData["ProyectoId"] = new SelectList(_context.Proyectos, "Id", "Id", tarea.ProyectoId);
            return View(tarea);
        }

        // GET: Tareas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarea = await _context.Tareas.FindAsync(id);
            if (tarea == null)
            {
                return NotFound();
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id", tarea.EmpleadoId);
            ViewData["ProyectoId"] = new SelectList(_context.Proyectos, "Id", "Id", tarea.ProyectoId);
            return View(tarea);
        }

        // POST: Tareas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombredelatarea,FechadeInicio,TiempoEstimado,EstadoProgreso,ProyectoId,EmpleadoId")] Tarea tarea)
        {
            if (id != tarea.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tarea);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TareaExists(tarea.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id", tarea.EmpleadoId);
            ViewData["ProyectoId"] = new SelectList(_context.Proyectos, "Id", "Id", tarea.ProyectoId);
            return View(tarea);
        }

        // GET: Tareas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarea = await _context.Tareas
                .Include(t => t.Empleado)
                .Include(t => t.Proyecto)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tarea == null)
            {
                return NotFound();
            }

            return View(tarea);
        }

        // POST: Tareas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tarea = await _context.Tareas.FindAsync(id);
            if (tarea != null)
            {
                _context.Tareas.Remove(tarea);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TareaExists(int id)
        {
            return _context.Tareas.Any(e => e.Id == id);
        }
    }
}

Views/Tareas/Create.cshtml
@model MiniCore.Models.Tarea

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Tarea</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombredelatarea" class="control-label"></label>
                <input asp-for="Nombredelatarea" class="form-control" />
                <span asp-validation-for="Nombredelatarea" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechadeInicio" class="control-label"></label>
                <input asp-for="FechadeInicio" class="form-control" />
                <span asp-validation-for="FechadeInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiempoEstimado" class="control-label"></label>
                <input asp-for="TiempoEstimado" class="form-control" />
                <span asp-validation-for="TiempoEstimado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstadoProgreso" class="control-label"></label>
                <input asp-for="EstadoProgreso" class="form-control" />
                <span asp-validation-for="EstadoProgreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProyectoId" class="control-label"></label>
                <select asp-for="ProyectoId" class ="form-control" asp-items="ViewBag.ProyectoId"></select>
            </div>
            <div class="form-group">
                <label asp-for="EmpleadoId" class="control-label"></label>
                <select asp-for="EmpleadoId" class ="form-control" asp-items="ViewBag.EmpleadoId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tareas/Delete.cshtml
@model MiniCore.Models.Tarea

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tarea</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombredelatarea)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombredelatarea)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechadeInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechadeInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TiempoEstimado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TiempoEstimado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoProgreso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstadoProgreso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empleado.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proyecto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proyecto.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Tareas/Details.cshtml
@model MiniCore.Models.Tarea

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Tarea</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombredelatarea)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombredelatarea)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechadeInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechadeInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TiempoEstimado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TiempoEstimado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoProgreso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstadoProgreso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empleado.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proyecto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proyecto.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Tareas/Edit.cshtml
@model MiniCore.Models.Tarea

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Tarea</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombredelatarea" class="control-label"></label>
                <input asp-for="Nombredelatarea" class="form-control" />
                <span asp-validation-for="Nombredelatarea" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechadeInicio" class="control-label"></label>
                <input asp-for="FechadeInicio" class="form-control" />
                <span asp-validation-for="FechadeInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiempoEstimado" class="control-label"></label>
                <input asp-for="TiempoEstimado" class="form-control" />
                <span asp-validation-for="TiempoEstimado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstadoProgreso" class="control-label"></label>
                <input asp-for="EstadoProgreso" class="form-control" />
                <span asp-validation-for="EstadoProgreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProyectoId" class="control-label"></label>
                <select asp-for="ProyectoId" class="form-control" asp-items="ViewBag.ProyectoId"></select>
                <span asp-validation-for="ProyectoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpleadoId" class="control-label"></label>
                <select asp-for="EmpleadoId" class="form-control" asp-items="ViewBag.EmpleadoId"></select>
                <span asp-validation-for="EmpleadoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tareas/Index.cshtml
@model IEnumerable<MiniCore.Models.Tarea>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="Index" asp-controller="Tareas" method="get">
    <div class="form-row">
        <div class="col-md-3">
            <label for="fechaInicio">Fecha de Inicio:</label>
            <input type="date" class="form-control" id="fechaInicio" name="fechaInicio" value="@((ViewData["fechaInicio"] as DateOnly?)?.ToString("yyyy-MM-dd"))" required>
        </div>
        <div class="col-md-3">
            <label for="fechaFin">Fecha de Fin:</label>
            <input type="date" class="form-control" id="fechaFin" name="fechaFin" value="@((ViewData["fechaFin"] as DateOnly?)?.ToString("yyyy-MM-dd"))" required>
        </div>
        <div class="col-md-3">
            <label>&nbsp;</label>
            <button type="submit" class="btn btn-primary btn-block">Filtrar</button>
        </div>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombredelatarea)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechadeInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TiempoEstimado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstadoProgreso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Empleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proyecto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombredelatarea)
                </td>
                <td>
                    @if (item.FechadeInicio.HasValue)
                    {
                        <text>@item.FechadeInicio.Value.ToString("dd/MM/yyyy")</text>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TiempoEstimado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstadoProgreso)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Empleado.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Proyecto.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>